export const SET_FIRST_TIME = "SET_FIRST_TIME";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_DEFAULT_APP= "SET_DEFAULT_APP";
export const SET_NUMBER_VERIFY= "SET_NUMBER_VERIFY";
export const SET_SESSIONS = "SET_SESSIONS";
export const SET_PROFILES= "SET_PROFILES";
export const SET_OWNERS= "SET_OWNERS";
export const SETINITIALROOT = "SETINITIALROOT";
export const SET_BRANDS = "SET_BRANDS";
export const SET_MODELS = "SET_MODELS";
export const SET_TYPES = "SET_TYPES";
export const SET_CARACTERISTICS = "SET_CARACTERISTICS";
export const SET_GEARBOX = "SET_GEARBOX";
export const SET_HIDE = "SET_HIDE";

export const SET_CARS = "SET_CARS";
export const SET_FACTURE = "SET_FACTURE";
export const SET_IMAGES = "SET_IMAGES";

export const LOGING_REQUEST = "LOGING_REQUEST";
export const LOGING_SUCCESS = "LOGING_SUCCESS";
export const LOGING_ERROR = "LOGING_ERROR";

export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_ERROR = "REGISTER_ERROR";

export const SET_REGISTERING_DATA = "SET_REGISTERING_DATA";

export const SMSCONFIRMATION_REQUEST = "SMSCONFIRMATION_REQUEST";
export const SMSCONFIRMATION_SUCCESS = "SMSCONFIRMATION_SUCCESS";
export const SMSCONFIRMATION_ERROR = "SMSCONFIRMATION_ERROR";
export const SMSCONFIRMATION_CONFIRM= "SMSCONFIRMATION_CONFIRM";

export const SET_CONFIRMATION_NUMBER= "SET_CONFIRMATION_NUMBER";
export const SET_CONFIRMATION_CODE= "SET_CONFIRMATION_CODE";

export const INITIALISE_CONFIRMATION= "INITIALISE_CONFIRMATION";

export const PASSFORGOT_REQUEST = "PASSFORGOT_REQUEST";
export const PASSFORGOT_SUCCESS = "PASSFORGOT_SUCCESS";
export const PASSFORGOT_ERROR = "PASSFORGOT_ERROR";

export const CAR_REGISTER_REQUEST = "CAR_REGISTER_REQUEST";
export const CAR_REGISTER_SUCCESS = "CAR_REGISTER_SUCCESS";
export const CAR_REGISTER_ERROR = "CAR_REGISTER_ERROR";
export const CAR_REGISTER_SETDATA = "CAR_REGISTER_SETDATA";
export const CAR_REGISTER_INPUTDATA= "CAR_REGISTER_INPUTDATA";

export const UPDATEOWNER_REQUEST = "UPDATEOWNER_REQUEST";
export const UPDATEOWNER_ERROR = "UPDATEOWNER_ERROR";
export const UPDATEOWNER_SUCCESS = "UPDATEOWNER_SUCCESS";